[tool.black]
line-length = 79

[tool.isort]
force_sort_within_sections = true
from_first = false
known_first_party = "ansible_collections.canonical.maas"
line_length = 79
profile = "black"

[tool.flake8]
exclude = ["tests/output/"]
ignore = ["E203", "E266", "E402", "E501", "W503", "W504"]
