- name: Create nic
  hosts: localhost
  tasks:
  - name: Create new nic on sunny-raptor host with VM new-machine
    canonical.maas.vm_nic_physical:
      instance:
        host: http://localhost:5240/MAAS
        token_key: URCfn6EhdZSj9CSDf7
        token_secret: PhXz3ncACvkcKnmCjsuSpzPnkf79pLPk
        client_key: nzW4EBWjyDe5B5szja
      vm_host: sunny-raptor
      hostname: calm-guinea
      state: present
      mac_address: '00:16:3e:ae:78:75'
      vlan: 5
      name: new_nic
      mtu: 1500
      tags:
        - first
        - second
    register: machine

  - debug:
      var: machine