- name: test query machines
  hosts: localhost
  tasks:
  - name: Create new machine on sunny-raptor host
    canonical.maas.vm_host_machine:
      instance:
        host: http://localhost:5240/MAAS
        token_key: URCfn6EhdZSj9CSDf7
        token_secret: PhXz3ncACvkcKnmCjsuSpzPnkf79pLPk
        client_key: nzW4EBWjyDe5B5szja
      vm_host: sunny-raptor
      cores: 2
      memory: 2048
      state: ready
    register: machines

  - debug:
      var: machines
