- name: Create nic and Delete nic
  hosts: localhost
  tasks:
  - name: Create new nic on crisp-skunk host with VM new-machine
    canonical.maas.tag:
      cluster_instance:
        host: http://10.44.240.10:5240/MAAS
        token_key: kDcKvtWX7fXLB7TvB2
        token_secret: ktBqeLMRvLBDLFm7g8xybgpQ4jSkkwgk
        customer_key: tqDErtYzyzRVdUb9hS
      state: present
      name: bla
      machines: []
    register: nic_info
