- name: Test query machines
  hosts: localhost
  tasks:
  - name: List machines
    canonical.maas.machine_info:
      cluster_instance:
        host: http://localhost:5240/MAAS
        token_key: URCfn6EhdZSj9CSDf7
        token_secret: PhXz3ncACvkcKnmCjsuSpzPnkf79pLPk
        customer_key: nzW4EBWjyDe5B5szja
      # fqdn: solid-fish # Use this field to filter results by name.
    register: machines

  - ansible.builtin.debug:
      var: machines
