- name: Create nic and Delete nic
  hosts: localhost
  tasks:
  - name: Create new nic on sunny-raptor host with VM new-machine
    canonical.maas.network_interface_physical:
      cluster_instance:
        host: http://localhost:5240/MAAS
        token_key: URCfn6EhdZSj9CSDf7
        token_secret: PhXz3ncACvkcKnmCjsuSpzPnkf79pLPk
        customer_key: nzW4EBWjyDe5B5szja
      fqdn: new-machine-3
      state: present
      mac_address: '00:16:3e:ae:78:75'
      # vlan: 5
      name: new_nic
      mtu: 1700
      tags:
        - first
        - second
    register: nic_info

  - debug:
      var: nic_info

  - name: Delete nic from machine calm-guinea on host sunny-raptor
    canonical.maas.network_interface_physical:
      instance:
        host: http://localhost:5240/MAAS
        token_key: URCfn6EhdZSj9CSDf7
        token_secret: PhXz3ncACvkcKnmCjsuSpzPnkf79pLPk
        client_key: nzW4EBWjyDe5B5szja
      fqdn: calm-guinea
      state: absent
      mac_address: '00:16:3e:ae:78:75'
    register: nic_info

  - debug:
      var: nic_info
