- name: test query machines
  hosts: localhost
  tasks:
  - name: List machines
    canonical.maas.vm_host_info:
      instance:
        host: http://localhost:5240/MAAS
        token_key: URCfn6EhdZSj9CSDf7
        token_secret: PhXz3ncACvkcKnmCjsuSpzPnkf79pLPk
        client_key: nzW4EBWjyDe5B5szja
    register: machines

  - debug:
      var: machines
