- name: test query machines
  hosts: localhost
  tasks:
  - name: List machines
    cannonical.maas.machine_info:
      instance:
        host: ...
        token_key: ...
        token_secret: ... 
        client_key: ...
    register: machines

  - debug:
      var: machines
