---
- name: Use user module
  hosts: localhost
  tasks:
    - name: Create user James
      canonical.maas.user:
        cluster_instance:
          host: http://10.44.240.10:5240/MAAS
          token_key: kDcKvtWX7fXLB7TvB2
          token_secret: ktBqeLMRvLBDLFm7g8xybgpQ4jSkkwgk
          customer_key: tqDErtYzyzRVdUb9hS
        state: present
        name: James
        password: james123
        email: james@email.com
        is_admin: false
      register: users
    - ansible.builtin.debug:
        var: users

    - name: Delete user James
      canonical.maas.user:
        cluster_instance:
          host: http://10.44.240.10:5240/MAAS
          token_key: kDcKvtWX7fXLB7TvB2
          token_secret: ktBqeLMRvLBDLFm7g8xybgpQ4jSkkwgk
          customer_key: tqDErtYzyzRVdUb9hS
        state: absent
        name: James
        is_admin: false
      register: users
    - ansible.builtin.debug:
        var: users
